import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Embedding
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

texts = [
    "Bugün hava gerçekten çok güzeldi",
    "Annem akşam yemeği için harika bir çorba yaptı",
    "Yeni çıkan kitabı hemen alıp okumaya başladım",
    "Kütüphanede ders çalışmak her zaman daha verimli oluyor",
    "En sevdiğim mevsim sonbahardır, yapraklar çok güzel",
    "Yarın erken kalkıp spor yapmayı planlıyorum",
    "Bu şarkı bana eski günleri hatırlatıyor",
    "Hafta sonu arkadaşlarımla sinemaya gideceğiz",
    "Uzun bir yürüyüşten sonra çok yorgun hissediyorum",
    "Güneş batarken gökyüzü turuncu ve mora döndü",
    "O sınavdan yüksek not aldığım için çok mutluyum",
    "Bilgisayarımın performansı son zamanlarda düştü",
    "Yeni bir dil öğrenmek her zaman ilgimi çekmiştir",
    "Kahvemi genellikle sütsüz ve şekersiz içerim",
    "Seyahat etmeyi ve yeni yerler keşfetmeyi çok seviyorum",
    "Bisikletimle ormanda uzun bir tura çıktım",
    "Bu resimdeki detaylar gerçekten çok etkileyici",
    "Bir fincan sıcak çay tam da ihtiyacım olan şeydi",
    "Onunla konuşmak her zaman ilham verici oluyor",
    "Dün gece çok ilginç bir rüya gördüm",
    "Şehir merkezindeki trafik sabahları çok yoğun oluyor",
    "Kendime yeni bir hobi edinmek istiyorum",
    "Balkonda oturup yağmur sesini dinlemek huzur verici",
    "Matematik dersi bana her zaman zor gelmiştir",
    "Daha fazla su içmeye dikkat etmeliyim",
    "Akşam haberlerini kaçırmamaya çalışıyorum",
    "Oraya trenle gitmek uçaktan daha keyifliydi",
    "Bu projeyi zamanında bitirmemiz gerekiyor",
    "Telefonumun şarjı çok çabuk bitiyor",
    "Gözlüklerimi yine kaybettim, nerede olabilir?",
    "Spor salonuna düzenli olarak gitmeye başladım",
    "Hayvanat bahçesindeki filler çok büyüktü",
    "Bence en iyi tatil deniz kenarında geçirilir",
    "Sıcak çikolata kış aylarının vazgeçilmezidir",
    "Eski bir arkadaşıma tesadüfen rastladım",
    "Bu hafta sonu biraz dinlenmeye ihtiyacım var",
    "Oyun oynamayı bırakıp ders çalışmalıyım",
    "Gelecek planları yapmak beni heyecanlandırıyor",
    "Bugün hiç beklenmedik bir misafirimiz vardı",
    "Çiçeklerin kokusu tüm odayı sardı",
    "Bu konuyu daha detaylı araştırmalıyız",
    "Sabahları erken uyanmakta zorlanıyorum",
    "En sevdiğim yemek annemin yaptığı mantıdır",
    "Bu caddede yürüyüş yapmak çok hoşuma gidiyor",
    "Televizyondaki o dizinin yeni bölümünü izledim",
    "Dizüstü bilgisayarım biraz eski, yenisini almalıyım",
    "Kendi işimi kurmak en büyük hayalim",
    "Müzik dinlemek stresimi azaltmama yardımcı oluyor",
    "Hava aniden soğudu, montumu giymeliyim",
    "Arkadaşımın doğum günü partisine davetliyim",
    "O anlattığı hikaye gerçekten çok komikti",
    "Bu ayakkabılarla çok rahat dans edebiliyorum",
    "Bazen sadece sessizliğe ihtiyacım oluyor",
    "Çocukluğumun geçtiği yerleri ziyaret ettim",
    "Tarihi filmleri izlemekten büyük keyif alıyorum",
    "Buzdolabımızdaki sebzeler tükenmek üzere",
    "Bu görevi başarıyla tamamladık",
    "Güneşli bir gün, neden dışarı çıkmıyoruz?",
    "Karar vermeden önce tüm seçenekleri değerlendirmeliyim",
    "Felsefe kitapları okumak ufkumu genişletiyor",
    "Elimdeki projede bazı teknik zorluklar yaşıyorum",
    "Bu tarifle yapılan kurabiyeler enfes olmuş",
    "Sürekli ertelemeyi bırakıp işe koyulmalıyım",
    "Şemsiyemi yanıma almayı yine unuttum",
    "Yabancı dilde film izlemek pratik yapmama yardımcı oluyor",
    "Hedefime ulaşmak için daha çok çalışmalıyım",
    "Bu elbise bana biraz büyük geldi",
    "Her sabah bir bardak limonlu su içiyorum",
    "Yaz tatili planları yapmaya başladık bile",
    "Yeni öğrendiğim bilgileri hemen uygulamaya koydum",
    "Köpeğim parkta oynamayı çok seviyor",
    "O toplantı çok uzun sürdü ve yorucuydu",
    "Geceleri yıldızları izlemek muhteşem bir duygu",
    "Hangi üniversiteye gideceğime karar veremedim",
    "Pazardan taze meyve ve sebze aldım",
    "Bu aralar çok fazla dizi izliyorum",
    "Banka işlerimi halletmek için dışarı çıkmam gerek",
    "Toplu taşımayı kullanmak daha ekonomik oluyor",
    "Eski defterlerimi karıştırırken anılarıma daldım",
    "Kitap okumak ruhumu dinlendiriyor",
    "Bu resmi yapmak için çok zaman harcadım",
    "Gereksiz eşyalarımdan kurtulmak istiyorum",
    "Bütün gün evde olmak canımı sıktı",
    "Akşamları yürüyüşe çıkmak iyi geliyor",
    "Bu konuda farklı bir fikrim var",
    "Tüm evrakları düzenlemeyi bitirdim",
    "Yeni bir fotoğraf makinesi almayı düşünüyorum",
    "Şehrin gürültüsünden uzaklaşmaya ihtiyacım var",
    "Birazdan önemli bir telefon görüşmesi yapacağım",
    "Bu yemeğin tadı biraz tuzlu olmuş",
    "Egzersiz yapmak enerjimi yükseltiyor",
    "Kendi kendime gitar çalmayı öğrendim",
    "Ona küçük bir sürpriz hazırladım",
    "Hayatımdaki değişiklikler beni heyecanlandırıyor",
    "Bu sorunun çözümü sandığımızdan daha basitmiş",
    "Tasarruf etmeye daha çok odaklanmalıyım",
    "Tatilde dinlenmek ve eğlenmek istiyorum",
    "Güneş kremi sürmeyi asla unutmuyorum",
    "Bu makale gerçekten çok bilgilendiriciydi",
    "Olay yerine en yakın bizdik",
    "Haftalık planımı yaparken ajandama notlar aldım",
    "Doğa yürüyüşleri yapmayı çok özledim",
    "Hedeflerime emin adımlarla ilerliyorum"
    "Gökyüzü bu sabah inanılmaz derecede berraktı",
    "Yeni bir yazılım dilini öğrenmeye karar verdim",
    "Eski bir fotoğraf albümünü karıştırırken nostalji yaşadım",
    "Kedim pencerenin önünde oturup dışarıyı izliyor",
    "Büyük annemin tarif defteri paha biçilmez değerde",
    "Spor salonuna üyelik yaptırarak daha aktif olmayı hedefliyorum",
    "Bu belgesel, uzay keşifleri hakkında ilginç bilgiler sunuyor",
    "Acil bir durumda ne yapılması gerektiğini biliyor musun?",
    "Mutfak dolaplarını yeniden düzenlemek epey zamanımı aldı",
    "Şehrin tarihi dokusu beni her zaman etkilemiştir",
    "Bir sonraki tatilim için detaylı bir gezi planı hazırlıyorum",
    "En zorlu problemi bile sabırla çözebiliriz",
    "Bu hafta sonu uzun zamandır beklediğim konser var",
    "Yaz mevsimi geldiğinde dondurma tüketimi artar",
    "Okulda yeni kurulan kulübe hemen üye oldum",
    "Eleştirel düşünme becerisi, eğitimde çok önemlidir",
    "Piyano çalmayı öğrenmek için derslere başladım",
    "Yağmurlu günlerde kitap okumak en büyük zevkimdir",
    "İş görüşmem çok başarılı geçti, umutluyum",
    "Tasarımını yaptığı web sitesi gerçekten çok modern görünüyor",
    "Market alışveriş listemi hazırlarken hiçbir şeyi unutmuyorum",
    "Deniz kenarında yürüyüş yapmak zihni dinlendiriyor",
    "Teknolojinin gelişimi hayatımızı kökten değiştirdi",
    "Egzersiz sonrası bol su içmek çok önemlidir",
    "Bu filmin sonu tamamen beklenmedikti",
    "Birleşmiş Milletler Genel Kurulu toplantısı ertelendi",
    "Finansal okuryazarlık her birey için gerekli bir beceridir",
    "Bahçedeki güller bu yıl daha canlı açmış",
    "Takım çalışması, projenin başarısını garantiledi",
    "Sosyal medyada zaman geçirmeyi azaltmaya çalışıyorum",
    "Tatilde yanıma sadece bir sırt çantası alacağım",
    "Yeni bir dil öğrenmek, yeni bir pencere açar",
    "Akşam yemeği için közlenmiş sebzeler hazırladım",
    "Şarj edilebilir piller kullanmak çevreye daha duyarlı bir seçim",
    "Sanat tarihi dersleri almaya başladım",
    "O anlattığı fıkra herkesi kahkahalara boğdu",
    "Bu yılki hedeflerimi net bir şekilde belirledim",
    "Sabah kahvaltısında taze sıkılmış portakal suyu içtim",
    "Yapay zeka, birçok sektörde devrim yaratıyor",
    "Otomobil lastiklerinin hava basıncını kontrol ettim",
    "Geçmiş deneyimlerden ders çıkarmak önemlidir",
    "Evdeki tüm lambaları LED ampullerle değiştirdim",
    "Yerel halk pazarı, organik ürünler için harika bir yer",
    "Bu konuya farklı bir açıdan bakmak gerekiyor",
    "Şemsiyemi yanıma almayı unutmasam iyi olacak",
    "Bütün gün süren bir eğitim seminerine katıldım",
    "Yeni taşındığımız semt çok sessiz ve huzurlu",
    "Doğru nefes teknikleri stresi azaltmada etkilidir",
    "Bu tarihi bina, yüzlerce yıllık geçmişe sahip",
    "Onunla yıllar sonra bir kafede karşılaştık",
    "Dijital güvenliğe daha fazla önem vermeliyiz",
    "Ağaç dikme etkinliğine gönüllü olarak katıldım",
    "Bu lezzetli pastanın tarifini almalıyım",
    "Güneş gözlüğümü evde unuttuğum için pişmanım",
    "Bir uzmandan kariyer danışmanlığı aldım",
    "Çocukluğumdan kalma bir hatıra kutusu buldum",
    "Eski radyodan klasik müzik dinliyorum",
    "Bu romanın karakter gelişimi gerçekten muazzam",
    "Toplantı notlarını titizlikle kaydettim",
    "Geri dönüşüm kutularını doğru kullanmaya özen gösteriyorum",
    "Dağ yürüyüşü yaparken muhteşem bir manzara ile karşılaştık",
    "Oturma odasının dekorasyonunu yenilemeyi planlıyorum",
    "Bu yeni yatırım fırsatı çok cazip görünüyor",
    "Hukuk fakültesinden mezun olduktan sonra avukat oldu",
    "Hayvanları koruma derneğine bağış yaptım",
    "Bütün gece gökyüzünü izleyerek fotoğraf çektim",
    "Bu makale, derinlemesine bir analiz sunuyor",
    "Zaman yönetimi becerilerimi geliştirmeliyim",
    "Deniz seviyesinin yükselmesi ciddi bir küresel sorundur",
    "Eğitim programını başarıyla tamamlayarak sertifika aldım",
    "Çay demleme sanatı, sabır gerektiren bir süreçtir",
    "Yurt dışına taşınma fikri beni heyecanlandırıyor",
    "Bu karmaşık denklemi çözmek epey uğraştırdı",
    "Uzaktan çalışmak, esnek saatler sağlıyor",
    "Arkadaşım bana el yapımı bir hediye verdi",
    "Bu sene kış sporlarına başlamayı düşünüyorum",
    "İş yerinde profesyonel gelişim eğitimleri aldık",
    "Güneş enerjisi, temiz enerji kaynaklarının başında geliyor",
    "Gönüllü olarak huzurevinde yaşlılara yardım ediyorum",
    "Bu sanat eseri, izleyicide farklı duygular uyandırıyor",
    "Gezegenimizi korumak hepimizin sorumluluğundadır",
    "Yeni bir bilgisayar oyunu piyasaya sürüldü",
    "Misafirler için çeşitli atıştırmalıklar hazırladım",
    "Haftalık bütçemi planlarken dikkatli olmalıyım",
    "Bu küçük kasaba, huzurlu bir yaşam sunuyor",
    "Çevrimiçi kurslarla kişisel yeteneklerimi geliştiriyorum",
    "O anlattığı hikaye, gerçekten ibret vericiydi",
    "Kuş sesleri eşliğinde uyanmak harika bir duygu",
    "Bu eski saatin tamir edilmesi gerekiyor",
    "Proje için gerekli tüm kaynakları topladım",
    "Balkonda saksı çiçekleri yetiştirmeye başladım",
    "Sağlıklı beslenme, uzun yaşamın anahtarıdır",
    "Yeni tanıştığım kişiyle ortak ilgi alanlarımız varmış",
    "Bu romanın film uyarlaması ne zaman çıkacak?",
    "Yazılım güncellemesi telefonumun performansını artırdı",
    "Fırsat buldukça şehir dışına kaçamak yapıyorum",
    "Doğada olmak bana her zaman enerji veriyor",
    "Yeni bir araştırma makalesi okuyarak bilgimi tazeledim",
    "Bu binanın mimarisi gerçekten hayranlık uyandırıcı"
    "Bisikletimden düşerek dizimi incittim",
    "Güneşli havayı fırsat bilip deniz kenarına gittik",
    "Bu yılki mezuniyet töreni gerçekten çok duygusaldı",
    "Yapay zeka etiği konusunda önemli tartışmalar sürüyor",
    "Annem bana el örgüsü bir kazak hediye etti",
    "Fırsat eşitliği, modern toplumların temel ilkesidir",
    "Bütün gece gökyüzünde kayan yıldızları izledim",
    "Yeni bir işletim sistemi kurmak biraz zaman aldı",
    "Bu lezzetli meyveyi ilk defa deniyorum",
    "Çocuklar parkta neşeyle oyun oynuyorlardı",
    "Tarihi eserlerin korunması büyük önem taşıyor",
    "Kitaplığımı alfabetik sıraya göre yeniden düzenledim",
    "Yarınki toplantı için detaylı bir sunum hazırladım",
    "Otel rezervasyonumuzu son anda iptal etmek zorunda kaldık",
    "Geri bildirim almak, gelişimin önemli bir parçasıdır",
    "Su tasarrufu yapmak için yeni yöntemler deniyorum",
    "Bütün gün süren elektrik kesintisi hayatı zorlaştırdı",
    "Hafta sonu bir dağ evinde kamp yapmayı planlıyoruz",
    "Bu belirsizlik ortamında karar vermek zorlaştı",
    "Sanat, duyguları ifade etmenin en güzel yoludur",
    "Çalışma masamın üzerindeki dağınıklığı topladım",
    "O anlattığı macera filmi gerçekten çok sürükleyiciydi",
    "Ödeme yöntemleri teknolojinin ilerlemesiyle değişiyor",
    "Bazen bir mola verip sadece dinlenmek gerekiyor",
    "Bu bölgenin kendine has bir kültürel mirası var",
    "Tüm evrakları tarayıcıdan geçirip dijitalleştirdim",
    "Kendi sebzemi yetiştirmek için küçük bir bahçe yaptım",
    "Bu müzeye ilk kez geliyorum, çok etkilendim",
    "Trafik kurallarına uymak her sürücünün görevidir",
    "Bilgisayarımın yedeğini düzenli olarak alıyorum",
    "Yeni komşularımız çok sıcakkanlı insanlar çıktı",
    "Sosyal sorumluluk projelerine gönüllü destek veriyorum",
    "Güneşin doğuşunu izlemek için erken kalktım",
    "Bu karmaşık sorunun basit bir çözümü olmalı",
    "Otomobillerin elektrikli versiyonları popülerleşiyor",
    "Farklı kültürlerden yemekler denemeyi seviyorum",
    "Haftalık ders programımı duvara astım",
    "Dostluklar, hayatın en değerli hazinelerindendir",
    "Bu yaz daha çok yüzme pratiği yapmalıyım",
    "İnternet bağlantımız aniden kesildi",
    "Televizyonda eski bir Türk filmi oynuyordu",
    "Bütçemi aşmamak için indirimleri takip ediyorum",
    "Meditasyon yapmak zihinsel dinginlik sağlıyor",
    "Yeni bir iş başvurusu için özgeçmişimi güncelledim",
    "Bu fotoğraf, anı yakalamak adına harika olmuş",
    "Yerel kütüphanede ilginç bir konferans vardı",
    "Küresel ısınmanın etkileri giderek artıyor",
    "Köpeğime yeni bir oyuncak aldım, çok sevindi",
    "Bu şehirde yaşamanın kendine özgü zorlukları var",
    "Yüzük parmağıma taktığım alyans parlıyordu",
    "Kamera ayarlarını manuel olarak yapmayı öğrendim",
    "Hayatımdaki öncelikleri yeniden gözden geçiriyorum",
    "Bu proje için ek bir bütçe gerekiyor",
    "Havaalanındaki güvenlik kontrolü çok uzun sürdü",
    "Toprak, bitkilerin yaşam kaynağıdır",
    "Bu sözleşmenin her maddesini dikkatlice okumalıyım",
    "Daha az plastik kullanmaya gayret ediyorum",
    "Yüksek sesli müzik dinlemek bazen rahatsız edici olabiliyor",
    "Bütün gün evde pijamalarımla tembellik yaptım",
    "Bu ayki elektrik faturası beklenenden yüksek geldi",
    "Bilim kurgu kitapları okumak hayal gücümü geliştiriyor",
    "Arabamın lastiği patladı ve yolda kaldım",
    "Yeni bir fotoğraf sergisi açılışına davetliydim",
    "Deprem tatbikatı başarılı bir şekilde gerçekleştirildi",
    "Gelecek için sağlam bir yatırım planı oluşturdum",
    "Daha düzenli bir uyku düzenine geçmeliyim",
    "Bu türkü, Anadolu'nun derin acılarını anlatıyor",
    "Yeni bir spor ayakkabısı almam gerekiyor",
    "Sürekli öğrenme, kişisel gelişimin anahtarıdır",
    "Odanın duvarlarını açık renge boyadık",
    "Sosyal medyadan gelen bildirimleri kapattım",
    "Bu tarifteki gizli malzeme biraz vanilyaymış",
    "Emek, her başarının temelinde yatar",
    "Balkondan sarkan sarmaşıklar çok güzel görünüyor",
    "Bu hatanın nedenini bulmak için çok uğraştık",
    "Bir hafta boyunca dijital detoks yapacağım",
    "Bu yemeği yapmak için tüm malzemeleri aldım",
    "Geç kalmamak için taksiye bindim",
    "Dünya çapında birçok gönüllü organizasyon var",
    "Bu kumaşın dokusu gerçekten çok yumuşak",
    "Yeni bir şifre belirlerken dikkatli olmalıyız",
    "Toplumsal konular hakkında farkındalık yaratmalıyız",
    "Sabah koşusu yapmak güne zinde başlamamı sağlıyor",
    "Onunla aramızdaki yanlış anlaşılmayı düzelttik",
    "Evdeki eski eşyaları bir hayır kurumuna bağışladım",
    "Bu makine, üretim sürecini hızlandırdı",
    "Kışın deniz suyu sıcaklığı oldukça düşüyor",
    "Kendi iç sesimizi dinlemeyi öğrenmeliyiz",
    "Bu konuyla ilgili farklı uzmanların görüşlerini okudum",
    "Saksıdaki çiçekleri düzenli olarak suluyorum",
    "Yeni bir şampuan denedim, saçlarıma iyi geldi",
    "Geniş açılı bir lens ile manzara fotoğrafı çektim",
    "Tüm engellere rağmen hedefine ulaşmayı başardı",
    "Bu romanın olay örgüsü çok karmaşık değil",
    "Küçük bir kasabada yaşama fikri kulağa hoş geliyor"
    "Daha iyi bir iş çıkarmak için detaylara odaklandım",
    "Kitap kulübümüzde bu ay harika bir roman tartıştık",
    "Göz doktorunda rutin kontrolümü yaptırdım",
    "Bu yılki kış olimpiyatları çok heyecanlı geçti",
    "Yüksek tansiyon, düzenli kontrol gerektiren bir durumdur",
    "Yeni bir elektrikli süpürge almayı düşünüyorum",
    "Akşam yemeği davetinde çok güzel vakit geçirdik",
    "Bu projenin teslim tarihini uzatmamız gerekebilir",
    "Güneşli havada yürüyüş yapmak metabolizmayı hızlandırır",
    "Sanatsal yeteneklerimi geliştirmek için kursa yazıldım",
    "Haftalık planımı yaparken ajandamı kullandım",
    "Tarihi bir olayı anlatan etkileyici bir film izledim",
    "Bu konuyu daha derinlemesine incelemek şart",
    "Pazartesi sendromu, genel olarak motivasyon düşüklüğünü ifade eder",
    "Bütün gün evde internetten araştırma yaptım",
    "Uluslararası ilişkiler, çok boyutlu bir disiplindir",
    "Doğru bilgiye ulaşmak için kaynakları kontrol etmeliyiz",
    "Yaz aylarında klima kullanmak kaçınılmaz oluyor",
    "Kendi iç sesime güvenmeyi öğrendim",
    "Bu yazarın anlatım dili gerçekten çok akıcı",
    "Yeni aldığım telefon kılıfı çok şık görünüyor",
    "Bir kaza sonucu arabamın farı kırıldı",
    "Eğitimde dijitalleşme süreci hız kesmeden devam ediyor",
    "Uzun vadeli hedefler belirlemek motivasyonu artırır",
    "Hafta sonu bahçede mangal keyfi yaptık",
    "Bu konudaki tüm riskleri hesaplamamız gerekiyor",
    "Çocukken en sevdiğim oyun saklambaçtı",
    "Bu tiyatro oyunu eleştirmenlerden tam not aldı",
    "Suudi Arabistan'da büyük bir inşaat projesi başladı",
    "Sabahın erken saatlerinde spor yapmak en iyisi",
    "Bütün gün süren toplantıdan sonra çok yorgunum",
    "Yeni bir yazılım sayesinde iş akışımız kolaylaştı",
    "Bu çiçek türü sadece bu bölgede yetişiyor",
    "Finansal özgürlüğe ulaşmak en büyük hayalim",
    "Odanın perdelerini değiştirerek havayı yeniledim",
    "Kuş gribi vakalarının yeniden arttığı bildirildi",
    "Bu zorlu görevi başarıyla tamamladığı için tebrik ettim",
    "Akşamları televizyon izlemek yerine kitap okuyorum",
    "Eski bir arkadaşımla sosyal medyada tekrar bağ kurdum",
    "Bu yılki vergi beyannamemi hazırlarken zorlandım",
    "Sırt çantamla Avrupa'yı gezmeyi hayal ediyorum",
    "Eğitim kalitesini artırmak için yeni müfredat hazırlandı",
    "Bu küçük kasaba, geleneksel mimarisini koruyor",
    "Tıbbi araştırmalar için gönüllü denek arıyorlar",
    "Sürekli ertelediğim o işi sonunda bitirdim",
    "Bu elbise bana çok yakıştı, hemen aldım",
    "Ağaçlar sonbaharda yapraklarını döküyor",
    "Sosyal becerilerimi geliştirmek için kitaplar okuyorum",
    "Bu tarihi anlaşmanın detayları hala tartışılıyor",
    "Kışın cildim çok kuruyor, nemlendirici şart",
    "İş yerindeki yeni projeye liderlik edeceğim",
    "Bu felsefi akım, modern dünyayı farklı yorumluyor",
    "Doğum günü partime çok sayıda arkadaşım geldi",
    "Bu şarkının sözleri gerçekten çok anlamlı",
    "Gelecek nesillere daha yaşanabilir bir dünya bırakmalıyız",
    "Sınav sonuçları açıklandı, herkes çok heyecanlıydı",
    "Bu evin mutfağı çok geniş ve kullanışlı",
    "Çocukluğumda en çok sevdiğim yiyecek makarnaydı",
    "Bu bölgedeki volkanik faaliyetler hala devam ediyor",
    "Enerjimi düşüren insanlardan uzak durmaya çalışıyorum",
    "Güneydoğu Asya mutfağına ilgi duymaya başladım",
    "Bu sorunu çözmek için beyin fırtınası yaptık",
    "Daha az tüketip daha çok üretmeyi hedefliyorum",
    "Akşam yemeği sonrası bulaşıkları hemen yıkadım",
    "Bu kış çok kar yağdı, çocuklar çok sevindi",
    "Yüksek lisans başvurum için referans mektubu istedim",
    "Bu filmin görsel efektleri gerçekten çok başarılı",
    "Bisiklet yolu, şehir içi ulaşımı kolaylaştırdı",
    "Hayat, beklenmedik sürprizlerle dolu bir yolculuktur",
    "Bu romanın ana karakteriyle kendimi özdeşleştirdim",
    "İnternet hızımız bu aralar çok yavaşladı",
    "Yeni bir araba almadan önce test sürüşü yaptım",
    "Bu yatırımın geri dönüşü uzun vadede gerçekleşecek",
    "Kitap okuma alışkanlığı edinmek çok faydalıdır",
    "Bütün gün süren yolculuktan sonra dinlenmeliyim",
    "Bu caddede her zaman çok kalabalık oluyor",
    "Doğal afetlere karşı hazırlıklı olmalıyız",
    "Bu konu hakkında bir uzmandan görüş alacağım",
    "Yeni aldığım kahve makinesi harika kahveler yapıyor",
    "İnsanlar arasındaki empati, toplumsal huzuru artırır",
    "Bu resmi yapmak için akrilik boya kullandım",
    "Gereksiz toplantıları azaltarak zaman kazandık",
    "Bu bölgenin bitki örtüsü gerçekten çok zengin",
    "Tatile çıkmadan önce evdeki tüm işleri bitirdim",
    "Bu şirketin yönetim kurulu başkanı istifa etti",
    "Akşam ezanı okunurken gökyüzü kızardı",
    "Bu zorlu süreçte birbirimize destek olmalıyız",
    "Gözümdeki alerji için doktora gittim",
    "Otelimizin manzarası doğrudan denize bakıyordu",
    "Bu küçük ayrıntı, tüm resmi değiştirdi",
    "Hedefime ulaşmak için yeni bir strateji geliştirdim",
    "Bu ceket, yağmurlu havalar için ideal",
    "Bütün gün süren fırtına nihayet dindi",
    "Bu tarifi yaparken tuzu biraz fazla kaçırdım",
    "Yurtdışı eğitim başvurumun sonucunu bekliyorum",
    "Daha fazla gönüllü çalışmaya katılmalıyım",
    "Bu makale, bilimin topluma etkisini inceliyor",
    "Trafik ışıklarında beklerken telefonuma baktım",
    "Bu işi bitirmek için ek mesai yapacağım"
]
#%% Metin temizleme ve preprocessing: tokenization , padding, label encoding
tokenizer=  Tokenizer()
tokenizer.fit_on_texts(texts) # metinler üzerindeki kelime frekanslarını öğren
total_words= len(tokenizer.word_index)+1
# n gram dizileri oluştur ve padding uygula
input_sequences=[]
for text in texts:
    token_list= tokenizer.texts_to_sequences([text])[0]
    for i in range(1,len(token_list)):
        n_gram_sequences= token_list[:i+1]
        input_sequences.append(n_gram_sequences)
#en uzun diziyi bulalım ve tüm dizileri aynı uzunluğa getirelim
max_sequences_length= max(len(x) for x in input_sequences )
# dizilere padding işlemi uygula yani hepsinin aynı uzunlukta olmasını sağla
input_sequences= pad_sequences(input_sequences, maxlen= max_sequences_length, padding="pre")
x=input_sequences[:,:-1]
y=input_sequences[:,-1]
y=tf.keras.utils.to_categorical(y,num_classes=total_words)
#LSTM modeli oluştur, compile, train ve evaluate
model= Sequential()
#embedding
model.add(Embedding(total_words, 50, input_length= x.shape[1]))
#LSTM
model.add(LSTM(100,return_sequences=False))
#output
model.add(Dense(total_words,activation="softmax"))
#model compile
model.compile(optimizer="adam",loss="categorical_crossentropy",metrics=["accuracy"])
#model training
model.fit(x,y,epochs=100, verbose=1)
#%% model prediction

def generate_test(seed_text, next_words):
    for _ in range(next_words):
        #girdi metinlerini sayısal verilere dönüştür.
        token_list = tokenizer.texts_to_sequences([seed_text])[0]
        #padding
        token_list= pad_sequences([token_list],maxlen= max_sequences_length-1, padding="pre")
        #prediction
        predicted_probabilities= model.predict(token_list, verbose=0)
        #en yüksek olasılığa sahip kelimenin indeksini bul
        predicted_word_index= np.argmax(predicted_probabilities, axis=-1)
        #tokenizer ile kelime index inden asıl kelimeyi bul
        predicted_word= tokenizer.index_word[predicted_word_index[0]]       
        #tahmin edilen kelimeyi seed_text e ekleyelim
        seed_text= seed_text+" "+predicted_word
    return seed_text
seed_text="annem"
print(generate_test(seed_text,7))






























